### ISSUE TITLE
How many community LDAP accounts show any activitiy in the past 12 months?

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#11]
**Knowns:**
* There are 1.696 accounts that are not explicitly disabled in the community tree of LDAP
* It's likely that less than half of those have seen any activity in the last year, but that's hard to quantify from LDAP data

**Objective:**
* Come up with a way to measure activity. @jdow has some ideas.

**Comment by gdestuynder** [comment]
@jdow I ran this for you using LDAP logs in MozDef (ie these are not auth0 logs, these are anything-ldap-login-successful-logs)
Results for 1mo are at: https://docs.google.com/spreadsheets/d/1UZKABN10w9V3UGIlT2sFVdgMmC4Qha962iHtA3f7CQI/edit#gid=472506515 (ask access)

Summary (unique users):
- 57 users in the last 30 days
- 139 users in the last 90 days
- 217 users since January 16th 2017
- 15 users logged in more than 3 times in the last 30 days
- 68 users logged in more than 3 times in the last 90 days
- 136 users logged in more than 3 times since January 16th 2017

I believe most of the users only login to change their password, in order to upload an SSH key to access mercurial (we don't have this data so this is an assumption, but I believe it is a very realistic one)

**Comment by gdestuynder** [comment]
SSH (as of today):
- 631 total, 292 community scm level 1 active users
- 397 total, 144 community scm level 2 active users
- 381 total, 140 community scm level 3 active users

Extracted from the new LDAP scm-active groups
