### ISSUE TITLE
User profile synchronization service between CIS and Auth0

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#114]
Story conceived in Q2 OKR Grooming Session.

**Acceptance criteria:**
- [x] Synchronization processor
- [x] A user profile in Auth0 matches a user profile in CIS

Note: This story replaces #57.

Size: M (3 days)

**Comment by gdestuynder** [comment]
Code with a class that updates a user from CIS to auth0:
https://gist.github.com/gdestuynder/b08f032378c6196c9de5c579ddc5514b
Rule that loads the updates:
https://github.com/mozilla-iam/auth0-deploy/pull/108

NOTE: this does not create new users yet though this is easy to add (will most likely be needed when Workday is integrated and LDAP is.. re-integrated, at some point)
NOTE2: due to issues with auth0 webtasks at the moment this has been implemented through an API call triggered by CIS instead of a webtask consuming a hook or getting triggered by a hook. Pretty similar in the end, both methods being triggers and not polling.
