### ISSUE TITLE
Sign message with Mozillians KMS Key

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#118]
Story conceived in Q2 OKR Grooming Session.

Size: n/a

Subtast to #117

**Comment by johngian** [comment]
This is partially implemented here:
https://github.com/mozilla-iam/cis/pull/9

What the merged code does is the heavy-lifting of the encryption/decryption process of the messages. CIS publishers just need to import this and encrypt their payload.

**Comment by andrewkrug** [comment]
@gdestuynder propose moving forward with encryption only to close this story and adding signing in sprint 8. ( Open a new story to describe signing the way we want )

**Comment by gdestuynder** [comment]
its already merged/coded anyway - but if we close this issue (#118) we'll have to open one to do this better/differently so that we can verify the validity of the change end-to-end.
this allows us for a bit more freedom in how we do CIS since it provides a high level security layer (if we implement it end-to-end that is)

**Comment by andrewkrug** [comment]
I have created a small python library to assist with signing https://github.com/andrewkrug/pykmssig

**Comment by gdestuynder** [comment]
iceboxed until we have a signing solution
we currently do encryption instead

**Comment by gdestuynder** [comment]
dupe https://github.com/mozilla-iam/cis_functions/issues/39
