### ISSUE TITLE
Include SCM levels (posix groups) in LDAP data sent as groups to auth0

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#144]
This blocks some RPs from moving over to auth0

Note: we might also want svn groups while at it?

**Comment by gdestuynder** [comment]
Note: should care for expiration settings on these if we do that

**Comment by gdestuynder** [comment]
@indygreg do you think this makes sense to send these groups?
Note that we can either just send them, or only send them if the access attribute says its not expired.

I'm asking you as hg is the primary user of them (and we thought, initially, the only user)

**Comment by jdow** [comment]
There are some issues around this that need special consideration. I'll outline them here.

Regular groups are known as groupOfNames groups (i.e. their structure objectClass is groupOfNames). These groups reference a DN attribute of a member.

Posix Groups (objectClass=posixGroup) on the other hand reference a uid attribute of a user.

SCM groups are a non-standard mozilla-only implementation. They are posixGroup objects, but rather than use uid attribute, they instead reference the "mail" attribute of the user in the memberUid attribute of the group. This has worked ok for us, because we've always controlled both the client and server side of any interaction around them. It is true that a special workaround has always been needed anytime we've had to do anything with them.

For auth0's ldap connector, I don't know if it supports posixGroups at all, but even if it does, it likely won't support the special variation that we have.

Unrelated to the above, but equally important consideration: membership in an SCM group is not intended to work the same way as any other group. The intended use of these groups is by mercurial systems at Mozilla. These systems use a second check in additon to the group membership check. They also check for the hgAccountEnabled (boolean) attribute on the user object (note that membership in scm group is on the group object, not the user object). The hgAccountEnabled attribute is separately maintained by a cronjob that looks at hgAccessDate, which is maintained by the mercurial servers.

So, bringing all this together, when a user intends to commit code to mercurial, to a repo that is restricted to a particular scm_level_* group, the following conditions must be met:
1) User must have a public SSH key as an attribute to their user object in LDAP
2) User must be a member of scm_level_*
3) User must have an hgAccessDate of less than 6 months ago
4) User must have hgAccountEnabled=TRUE (which should happen automatically if the first three conditions are met).

Abstracting from the technical aspects, the various attributes have specific meanings:
1) Membership in the scm_level_* group conveys a level of trust that has been established between the user and Mozilla per the Hacking policy.
2) The state of hgAccountEnabled being FALSE does not indicate a loss of trust between Mozilla and the user.
3) The purpose of the two-part system is because users that commit to mercurial are not bound to Mozilla via employment or any other system that tracks whether they are active in the code development process, nor do we know or control the environment that the user operates in, or how well they protect their own credentials. If a user has not committed code in 6 months and then wants to start committing again, we have no way of knowing whether it's the same person or if someone else gained access to that user's ssh key. The purpose of access expiring is simply an attempt to protect against credential re-use by 3rd parties.
4) A user who has expired hg access can get their account re-enabled simply by filing a bug asking for the access back. These bugs get automatically approved and done by any MOC employee as a standard operationg procedure. There is no process to gain trust as there was for the original inclusion in an SCM group, as per point 3 above, the trust is tied to the group membership, not the access date. The trust does not expire.

Now, that we've laid out the whole system, I'll note that in the past when people have asked me for a list of scm_level_3 users or similar, I generally ask the question: you want everyone in the group, or only the ones that could commit to hg scm_level_3 restricted repos today with no special action, i.e. you want the whole group, or just the ones that aren't currently expired? Almost always the answer is "just the ones that are not expired".

It appears that over the years, various other systems are making use of the scm level groups, as I've had to explain how they work many times to various folks working on various systems, and obviously this issue exists, which indicates that something other than mercurial cares about SCM groups.

So, all this boils down to the question of, do we want auth0 RPs to use these groups because they care about the trust level conveyed by the group membership, or do they want to be involved in the mercurial pipeline that makes use of both the group and the expiration state?

On a technical level, the most correct way for me to enable any SCM groups to show up in auth0 would be to write a little cron script that copies the membership list of the SCM groups to a new group that uses groupOfNames objectClass. This would need to have a different name both because (cn=scm_*) is a common filter specifically used to identify the actual SCM groups, and also because these groups are in the same tree as regular groups, so we can't have two scm_level_3 groups.

I propose such a cron script would create something like cn=current_scm_level_3 and cn=expired_scm_level_3 groups and would split the real scm_level_3 users into two groups based on their expiration state. Then an RP can do whatever they want with the information provided and the information in this comment to make a valid decision about how to use this data.

I'm also open to other suggestions.

**Comment by purelogiq** [comment]
Thanks @jdow! I'm going to talk to my team to see how this affects us and if we will go with your cron job idea or rethink how we're using scm levels.

(To give you some background, we're moving the 'click to autoland' feature out of MozReview and into a new service which we hoped to rely soley on Auth0 for. scm_levels were our plan for determining whether a user can land code or not, and that is still the plan, but, we will discuss it)

**Comment by purelogiq** [comment]
Hi @jdow, I talked with the team and it sounds like your plan will work for us. 

In our case we are just checking to see if the, for example, the user has ever been approved for scm_level_3 - even if their direct push access has expired (since in our case a user logging in via Auth0 is confirmation that they are still active, and since using autoland doesn't refresh the 6 month expiration we assume most people will have their direct push access expired).

Using your proposed plan, would it be correct for us to check the LDAP groups to see if the user is in *either* the current_scm_level_3 group or expired_scm_level_3 group and if so permit them to autoland code?

If the way we're using this sounds right, then we would greatly appreciate being able to access these fields via Auth0. Thanks! 😃

**Comment by indygreg** [comment]
CC @globau

I think some kind of "federation" between SCM group membership and auth0 is needed because right now our mechanism for trying to associate LDAP accounts to say BMO accounts or GitHub accounts is... complicated and a PITA. But as @jdow says, the group membership is kinda wonky because it... isn't just about group membership: there's also an active bit. But I don't think anything outside the Mercurial servers themselves looks at the active bit. So until those want to integrate with auth0, I wouldn't worry about its existence.

Honestly, the whole LDAP scm_ groups bit is outdated and needs to be replaced.  Bug 1226410 tracks some of the issues. But it generally works and changing it is hard. So justifying that work is difficult. We're probably best off cargo culting the existing groups to auth0 and kicking the overhaul can down the road, just like we've been doing for the past few years :)

**Comment by jdow** [comment]
I've shipped an update to my script that generates certain LDAP groups to include creating and maintaining some new groups. This script runs once per hour (so the new lists should be in sync with the real scm groups with no more than an hour of lag). It does the following:

For every existing scm_* group, it creates three new groupOfNames style groups, and keeps them up to date to match the real scm_groups. The new groups will be named like this:
For scm_level_1 group, there will be:
active_scm_level_1
expired_scm_level_1
all_scm_level_1

where the active_* group contains users that are in scm_* and have hgAccountEnabled=TRUE; expired_* group contains users that in the matching scm_* group and have hgAccountEnabled=FALSE; and the all_* group contains all users in the matching scm_* group.

So, a person that is active and in scm_level_1 will be present in both active_scm_level_1 and all_scm_level_1 groups, which will both show up in their auth0 groups profile.

With this logic in place, we'll leave it up to RPs to decide whether they want to use active_* or all_* for a given scm group (it sounds like in this particular issue, only the need for all_* is there, but I know there are other use cases out there where a distinction between active and expired is needed, so this way we maintain the integrity of that state for RPs that care).

**Comment by gdestuynder** [comment]
Note that the new user profile for Mozilla IAM supports authoritative groups that have expiration time.
When the time comes to integrate with 'auth0' I would highly recommend deprecating the above groups ( `{active,expired,all}_scm_level_{1,2,3}`) and replace the functionality.
The authoritative groups are per `client_id` (ie if you would want 3 you'd want 3 client ids) and are enforced during authentication.

This would also need to use [BeyondSSH](https://mana.mozilla.org/wiki/display/~gdestuynder@mozilla.com/Beyond+SSH) if using the SSH transport, or some kind of Mercurial wrapper otherwise (regardless of the group functionality, these solutions are used to authenticate with the SSO)

**Comment by purelogiq** [comment]
@jdow Thanks a million for the fix, it makes our use case a lot simpler and secure.

@gdestuynder Do you have a link or other information about these authoritative groups? Are these specific to LDAP or Auth0? Just curious, thanks.

**Comment by gdestuynder** [comment]
they're specific to Mozilla, it's a feature we're working on rolling out as part of our user profile
it looks like that: https://github.com/mozilla-iam/cis_functions/blob/feature/idvtoauth0/functions/validator/event.json#L87
