### ISSUE TITLE
Develop CIS POC

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#62]
- Define requirements 
     - Queuing
     - Business integration logic (may fall under the LDAP POC)
- Perform design validation of Change Integration Service
     - Validate inputs ( from mozillians.org/workday integration, determine data storage method)
          - Define and implement data retrieval method 
     - Transformation (Queuing system, LDAP SQL back-end, 
     - Integration (posting/insert data to LDAP profile)

**Comment by andrewkrug** [comment]
I did kind of a spike on this because I had a few extra cycles over the last couple days.  https://github.com/mozilla-iam/ldap-postgres-reference/tree/kinesis_streams

Most of the work is there.  @akatsoulas will sync in the coming days on this story and try to clarify some of the requirements around queueing.  @gdestuynder and I are thinking kinesis streams could be a good fit for our queue but we need to ensure the solution is workable for all.

**Comment by gdestuynder** [comment]
Brief/diagram https://docs.google.com/document/d/1eoQ5K3bTCuUYaTGmLtFSdNq-hzXZCRM4Cjuhw1Vv6rI/edit#heading=h.3eafe3kieqsw

**Comment by hmitsch** [comment]
In the _Q2 OKR Grooming Session_ this epic was decomposed into:

* #117: Write user profile to stream (From Mozillians.org)
    * #118 Sign message with Mozillians KMS Key
* #119: Setup Kinesis input stream
* #120: Setup CI
* https://github.com/mozilla-iam/cis/issues/7: Write Stream Processor Validator
* #121: Write Stream Processor Identity Vault Connector
* #122: Setup Identity Vault
* #114: Write Stream Processor Identity Driver Connector for Auth0
* #124: AWS Monitoring/Metrics
* #116: RP Handle new group information
* (optional) Write Stream Processor Identity Driver Connector for LDAP (not OKR)

For details, see https://docs.google.com/drawings/d/1cbAXP3-7rFprMr5tUaoGAOcvJBqRpSQlL4gT7OrUTCw/edit
