### ISSUE TITLE
SSO Dashboard Alert/Notification - UI Design

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#96]
Moving this task to its own issue (from #53) as it will be implemented during a later release date, currently TBD.

-----

Design Alert & Notification UI for the Auth0 SSO Dashboard, [user stories for reference](https://docs.google.com/a/mozilla.com/document/d/1xZaDKYcZGT9rMZfWtqWFek9onnXVPZOiRq8SUlgaGkw/edit?usp=sharing).

**Comment by mbransn** [comment]
@andrewkrug @hmitsch -- Initial iterations for notification/alert styling are ready for perusal. I have not yet worked through a notification center page, but have it in mind for next sprint. 

Banners accounted for are alert, success and general security. A menu badge and notification counter are also represented here. When a user selects 'more info' ideally they will be routed to the notification center which houses notification details and any user actionable item (approve/deny). Do we have access to 'more info' in order to design this step?

**Alert**

![alert-notification-banner](https://cloud.githubusercontent.com/assets/18686986/25598526/642fd18a-2e8a-11e7-9176-13dc920bbeff.png)


**Success**

![success-notification-banner](https://cloud.githubusercontent.com/assets/18686986/25598529/697e4d24-2e8a-11e7-80ea-518f60d93c2f.png)


**General Security**

![security-notification-banner](https://cloud.githubusercontent.com/assets/18686986/25598535/6f94693c-2e8a-11e7-80b2-d6ac8cdf8e76.png)

**Menu Badge & Counter**

![notification-menu-counter](https://cloud.githubusercontent.com/assets/18686986/25598537/76020f22-2e8a-11e7-990a-195035c8e04f.png)

**Comment by comzeradd** [comment]
These look great!

One minor comment is that that most people (especially non-OSX users) are used to have the 'close' button on the right side, on windows, alerts, etc. But I get that we also we want to emphasize the call to action.

**Comment by mbransn** [comment]
Thanks @comzeradd that's great to point out. I did play with the 'close' next to the 'more info' CTA, though things felt congested? I'll give it another go and also try moving 'close' to the end of the alert text.

@andrewkrug I'm curious re: the functionality of the notification center (navigated to via 'notifications' in the user menu). In the user stories we're calling out user acknowledgement of alerts, do you see this happening in the banner or in the notification center?

Also UX on these banner actions:
- 'more info' routes users to the notification center with the detail info for that notification expanded. In that view a user can take necessary actions (acknowledge, approve/deny, delete...)
- 'close' simply dismisses the banner on the dashboard, but keeps that notification in the notification center until a user interacts with it.

**Comment by andrewkrug** [comment]
@m-branson I like this but there's a few things I want to clarify about our alert use cases and maybe that will clear things up.  I think maybe we're (InfoSec) also guilty of not thinking the entire alert thing through here and scoping our feature set for this initial alert center release.  I'm going to try and define that.  

I think this is a good base to use and I like the highlight colors.  I just want to call out the additional use cases which I've done here: 

https://github.com/mozilla-iam/sso-dashboard/blob/master/docs/alert-center.md

**Comment by jeffbryner** [comment]
May need to sync on the levels? @gdestuynder

**Comment by mbransn** [comment]
@andrewkrug this is super helpful! Thank you!

Question re: alert severity and UI coloring -- can _High Level_ and _High Level Alert_ both be considered a 'red' level alert? Here's what I'm thinking so far:

- Information : black
- Warning : orange
- High Security : red
- High Security Alert : red
- Success : green _(shows when no user action is required other than observation, e.g. new app access has been added for a user)_

I'll work on UI for the alert center as well based on the schema you outlined. 🌮 🎉

**Comment by jeffbryner** [comment]
FWIW: Here's our current standard levels/colors for other systems. May not directly translate to the dashboard given the branding, but might at least help with terms: 
https://wiki.mozilla.org/Security/Standard_Levels

**Comment by mbransn** [comment]
Thanks @jeffbryner that is helpful and raises another question, do we need a 'success' banner at all? Or would an alert like _new app access granted_ simply fall into the 'low risk' category?

@andrewkrug @gdestuynder let me know when you get the levels ironed and I'll take colors from there. 👍

**Comment by mbransn** [comment]
I suppose this is also a good time to clarify that while we're looking at 'alerts' in this ask, we are also looking at 'notifications' in general. So this makes me believe that, yes, accounting for a success/error banner state as well is helpful. Not all notifications will be alerts.

**Comment by jeffbryner** [comment]
Yeah, a success banner makes sense to me for positive notifications.

**Comment by gdestuynder** [comment]
I made a PR for this at https://github.com/mozilla-iam/sso-dashboard/pull/123
The color, names and risk definitions are standardized and have been reviewed countless times.

Note that it's possible to not use the standard colors as long as they don't deviate too much (ie blue should be blue, yellow should be yellow, but they do not need to be the exact yellow used by the standard if it causes UI consistency issues). Additionally, since it seems easier to have generic alerts that also give you non-security and risk-zero alerts (such as "we moved your icon around!") from a UX pov - I would reserve LOW risk for these and never display the risk estimation or color in this case (this is what LOW risk is: we think there is no risk).

It's also possible to change the wording in the doc to separate alerts from low-risk alerts (ie pure notification) to make this more clear. It's also possible to do a lot of things in a different manner, such as only using the standard color in a "risk level" button but color the whole notification differently, or to use only certain risk levels as long as they do match expectations.

Hope this helps. Also if it does not I will still request for standards to be somewhat enforced /me evil laugh 👿  

_the point though is that we use risk across the board and consistent communication goes a long way, so if we can have it without making the UX bad that would be good._

**Comment by mbransn** [comment]
Thanks @gdestuynder! This is what I needed to see, appreciate the point toward security/standard levels. I'll align the banner UI colors with the standard, but do plan to account for the new brand in the color selection (e.g. blue will be a new Mozilla blue). And agreed, it makes sense to use LOW risk alerts for all non-security/risk-zero/general info type alerts.

**Comment by mbransn** [comment]
@andrewkrug @gdestuynder @jeffbryner @comzeradd @hmitsch -- Notifications have been updated to align with the [security/standard levels](https://wiki.mozilla.org/Security/Standard_Levels), this includes: alert levels, colors and user actions.

For high- and max-risk alerts, users must choose to engage with the banner as they do not have a dismiss 'x'. The medium-/low-risk alerts and the success message allow users to interact further or dismiss.

Notification center UI is also included, in this view users are provided with more info and the ability to interact as necessary with each alert. Thoughts?

**Max Risk**

![max-risk](https://cloud.githubusercontent.com/assets/18686986/25828654/4081471a-3406-11e7-8074-95756b0ef4b6.png)
_In Max Risk instances I'm asking users to get more info (i.e. go to notification center) before they decide to verify or deny, thoughts?_


**High Risk**

![high-risk](https://cloud.githubusercontent.com/assets/18686986/25828695/84468230-3406-11e7-9aa9-593703be4bf1.png)

**Medium Risk**

![medium-risk](https://cloud.githubusercontent.com/assets/18686986/25828700/8b891dfa-3406-11e7-8e1d-4a04e3ab4e26.png)

**Low Risk / General Notification**

![low-risk](https://cloud.githubusercontent.com/assets/18686986/25828709/9afb3a2a-3406-11e7-9709-d4f4bca59fe9.png)

**Success**

![success](https://cloud.githubusercontent.com/assets/18686986/25828714/a2083368-3406-11e7-8eb3-51345d84fd56.png)

**Menu Counter UI**

![menu-counter](https://cloud.githubusercontent.com/assets/18686986/25828825/467c92d6-3407-11e7-9ddd-93e2def97a06.png)

**Notification Center**

![notification-center](https://cloud.githubusercontent.com/assets/18686986/25828720/ab565292-3406-11e7-8df4-2a34826be084.jpg)

**Comment by gdestuynder** [comment]
_/me thinks this looks neat._
Note: we should probably not have "From mozdef" as part of the msg (even thus it is probably from mozdef :)

Note, maybe we want to come up with some realistic alerts scenarios that will help fine tune the UX, for example:

> High risk: We noticed that your account has logged in to signing1.firefox-signing-server.mozilla.com via SSH and it is a sensitive server. Was this really you? [Yes] [Yes, don't remind me for a week] [OMG call someone now] [More info]

Another one:
> Medium risk: Heads up, you just logged in from Taipei, but we previously have seen you from the San Francisco office 14 hours ago. Did you just move [Yes] [Yes don't remind me.. ] [Nope!!] [More info]

Another one:
> Maximum risk: Your account has authenticated to ssh.mozilla.com using 4 different IP addresses after failing to authenticate 104 times. Is this normal? [Yes] [Nope, help]

^^ I'm assuming maximum risk alerts will never have a "dont remind me" and will be also investigated regardless by us

**Comment by jeffbryner** [comment]
Love it! Might be worth someway for the user to enter some optional text for the max risk items? 

The 'faster than lightening/superman' scenario is a good one to play with. 

We do have folks that occasionally use tor/vpn that will appear to have moved around the globe. So they could dismiss and note that they are a tor user. 

If they didn't actually switch countries and don't use vpn/tor, they could add some text as well for context that might help us.

In general though I think the basic UI elements are right: Risk levels, Ack/Nack buttons, URL for clicking (for updates, etc). 

The Don't remind me might be useful, but seems like it would require heavy user state/customization? @andrewkrug 
The optional text might also be useful assuming we have a way to capture it and return it to mozdef @andrewkrug @pwnbus ?

**Comment by andrewkrug** [comment]
I think we've nailed the "look" overall.  Do you think we should draw some clear lines about what the alert center looks like in Release 1.0 ( no user customization etc ) and really scope that.  It feels a little like we're trying to design all the features at once.  We could likely accept this story as is and build out alert functionality with what exists in the above mock ups.

**Comment by andrewkrug** [comment]
Also do we want someone to be able to suppress an alert forever?  Seems like if we have alerts that are high false positives they should report the false positive and we should fix the alert rather than have a suppression feature.  Suggest button like ( Was this relevant ) or something to collect that data prior to deciding on alert suppression.

**Comment by mbransn** [comment]
@gdestuynder @jeffbryner @andrewkrug thank you for feedback, glad this is sparking good conversation re: functionality! I agree with Andrew re: nail down the scope for Release 1.0 and identify enhancements for future releases. 

At a baseline this UI will work for all of the instances that you've outlined @gdestuynder --- from a UX perspective if users are going to be given multiple ack/nack options we should be doing it in the notification center (meaning the banner simply utilizes a 'more info' on these -- not sure if you were/weren't suggesting more buttons in the banners, but want to be clear 😄). Banners should be a 'bite size' amount of info that gets our users attention and provides a route to the detailed information. Ideally we avoid users blindly ack/nack'ing without consuming relevant information.

@jeffbryner the optional info entry idea is a good one. What if this field 'appeared' after a user ack/nack'd allowing them to optionally submit add'l details? The benefit of this would be less cognitive load on the user (we want them to first focus on ack/nack) and result in an entry field that can be used for either submission (meaning less real estate on smaller devices).

@hmitsch do you have input here on the release scope?

**Comment by jeffbryner** [comment]
Yup, agreed on starting small (we've a lot to build just to get alerts to the dashboard) and focus on the base UI.

Agree with the info entry field appearing after choosing a path, good point!

**Comment by pwnbus** [comment]
@jeffbryner For the mozdef feedback part, we have I think 2 options here if the user selects "no, this wasn't me":
1. The SSO dashboard is the one who performs the escalation/action without sending any feedback info to mozdef. This would be less moving parts since there wouldn't be a feedback loop to MozDef, but IMO, would be mixing a SIEM functionality into the SSO.

2. The dashboard would talk back to mozdef, saying this alert was confirmed as a problem, and then Mozdef is the one who handles performing the escalation/action we define. The problem here would be that MozDef would have to be opened up to the dashboard so that the dashboard could send it's feedback.

Looking at it from a functional point of view, I think having MozDef be the one who handles the escalation/action makes the most sense, however, exposing MozDef so that SSO could communicate to MozDef could be a concern.

Feel free to loop us in and we can sit down and agree on the functional requirements.

**Comment by jeffbryner** [comment]
Yeah, I think the feedback needs to go to mozdef for proper handling/recording/history/etc. Integration shouldn't be that big of a deal using SNS/SQS to mediate the messages.

**Comment by andrewkrug** [comment]
@jeffbryner You have described something very similar to how I planned to do this integration with MozDef

**Comment by pwnbus** [comment]
@jeffbryner @andrewkrug Works for me

**Comment by jeffbryner** [comment]
Also, @m-branson  was reminded from another conversation of the need to potentially prompt for MFA verification (DUO push, or enter 6 digit code) for some alerts which may affect the UX. Probably just the highest severity.

**Comment by mbransn** [comment]
@jeffbryner good to know, will MFA be triggered after acknowledgement in those instances?

Also, who is owning/writing the functionality scope for this feature? Ideally we get this outlined so that the UI is dialed accordingly by end of this sprint. (Would love to hand off to @comzeradd for implementation next sprint.)

**Comment by gdestuynder** [comment]
Regarding the "dont remind me" feature I just remember several companies who implemented this saying it was key to success - even thus these still come up, otherwise user fatigue occurs very quickly.
Say user X logs in 10 times today to a sensitive server, and another 10 times in 2 days, he's going to get 10 msgs then 10 msgs again, then probably buy weapons of mass destruction and visit us ;p

The alternative of course, is to be very careful about what we alert on at the start, and precisely log/look at what is sent to users at least until we get that feature.

As a user, if I get a lot of these also i guess id like to have notification support in the browser, that brings me to the alert page directly (\o/)  @andrewkrug

**Comment by andrewkrug** [comment]
@gdestuynder sounds like you could solve this issue with batching and rate limiting.  I agree with this statement 👍 

> Say user X logs in 10 times today to a sensitive server, and another 10 times in 2 days, he's going to get 10 msgs then 10 msgs again, then probably buy weapons of mass destruction and visit us ;p

Can we do de-dupe at some point or something.

**Comment by hmitsch** [comment]
Hi @andrewkrug @jeffbryner @gdestuynder, 
Hey @m-branson,

I have a very naive question. Please be patient with me.

In my mental model there are two _notions_ of security alerts:
* **Non-profile** alerts: based on things such as browser version, IP address, etc.
* **Profile-based** alerts: based on a person's profile attributes, such as 'last login', application xyz added, etc.

At this moment the SSO Dashboard does not create user profiles nor does it connect to the Mozillians.org API to read or write profile attributes.

For this reason I suggest to narrow the **v1 scope** for _Alerts & Notifications in the SSO Dashboard_ to **non-profile alerts**. 

This would be the **green line** in the functional architecture below picture:
![2017-05-sso dashboards alerts v1 scope](https://cloud.githubusercontent.com/assets/869692/25912496/c7b34636-35b7-11e7-92c8-925a90af265a.png)


What are your thoughts on this? Am I having the wrong mental model?

Best regards,
   Henrik

**Comment by mbransn** [comment]
@andrewkrug based on the IAM chat + @hmitsch's thoughts above, can you update the [alert center doc](https://github.com/mozilla-iam/sso-dashboard/blob/master/docs/alert-center.md) to reflect functional scope for an initial release?

**Comment by gdestuynder** [comment]
@hmistch I think what you call _non profile alerts_ are what we would usually categorize as **low** and **medium** **risk** alerts. We base the alerts primarily on risk rather than how they're generated.
I think it makes sense to scope v1 to low and medium risk alerts, ie _non profile alerts,_ ie "yes" :)

Note: the dashboard does not and will most likely not communicate directly with mozillians.org - AFAIK - it currently gets all profile data from auth0 and when CIS is completed, will get the data from Mozillians.org as well through these means. The actual alerts though will most likely be sourced from mozdef, either directly or by having mozdef tell CIS about it.

**Comment by hmitsch** [comment]
@gdestuynder thank you for the clarification on the technical architecture. Sounds all very reasonable!
Also thanks for confirming the scope proposal. Let's work towards these _non-profile alerts_ (aka _low and medium risk alerts_).

**Comment by mbransn** [comment]
Implementation of low- and med-risk UI has been requested via the SSO repo [(#130)](https://github.com/mozilla-iam/sso-dashboard/issues/130). Closing this issue.
